
# https://github.com/sasstools/sass-lint/tree/develop/docs/rules

# The following scss-lint Linters are not yet supported by sass-lint:
# ElsePlacement, PseudoElement, SelectorDepth, TrailingWhitespace, UnnecessaryParentReference
# The following settings/values are unsupported by sass-lint:
# Linter PropertySortOrder, option "separate_groups"

files:
  include: '**/*.scss'
options:
  formatter: stylish
  merge-default-rules: false
rules:
  # enforce how many elements a BEM selector can contain
  bem-depth:
    - 0
    - max-depth: 2
  # enforce whether one should use 0 or none when specifying a zero border value
  border-zero:
    - 0
    - convention: zero
  # enforce the use of the chosen brace style
  brace-style:
    - 2
    - style: 1tbs
      allow-single-line: true
  # enforce a convention for class names
  class-name-format:
    - 2
    # - convention: hyphenatedlowercase
    - convention: strictbem
  #  enforce whether or not @import paths should have leading underscores and/or filename extensions
  clean-import-paths:
    - 2
    - filename-extension: false
      leading-underscore: false
  # enforce whether or not parenthesis should be included if no arguments are defined or used, when declaring or invoking a mixin
  empty-args:
    - 0
    - include: true
  # enforce whether or not nested blocks should include a space between the last non-comment declaration or not
  empty-line-between-blocks:
    - 2
    - include: true
      ignore-single-line-rulesets: true
  # enforce that extends should be written before declarations in a ruleset
  extends-before-declarations: 2
  # enforce that extends should be written before mixins in a ruleset
  extends-before-mixins: 2
  # enforce whether or not files should end with a newline
  final-newline:
    - 2
    - include: true
  # enforce the nesting of attributes
  force-attribute-nesting: 0
  # enforce the nesting of elements
  force-element-nesting: 0
  # enforce the nesting of pseudo elements/classes
  force-pseudo-nesting: 0
  # enforce a convention for function names
  function-name-format:
    - 2
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  # enforce the length of hexadecimal values
  hex-length:
    - 2
    - style: short
  # enforce the case of hexadecimal values
  hex-notation:
    - 2
    - style: lowercase
  # enforce a convention for ids
  id-name-format:
    - 2
    - convention: camelcase
      allow-leading-underscore: true
  # enforce an indentation size (in spaces) and ensure that tabs and spaces are not mixed
  indentation:
    - 2
    - size: 2
  # enforce whether or not decimal numbers should include a leading zero
  leading-zero:
    - 2
    - include: true
  # enforce a convention for mixin names
  mixin-name-format:
    - 2
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  # enforce that mixins should be written before declarations in a ruleset
  mixins-before-declarations: 2
  # enforce how deeply a selector can be nested
  nesting-depth:
    - 2
    - max-depth: 2
  # enforce the use of hexadecimal color values rather than literals
  no-color-keywords: 2
  # disallow the use of color literals and basic color functions in any declarations other than variables or maps/lists
  no-color-literals:
    - 2
    - allow-rgba: true
  # enforce the use of Sass single-line comments and disallow CSS comments. Bang comments (/*! */, will be printed even in minified mode) are still allowed
  no-css-comments: 2
  # enforce that @debug statements are not allowed to be used
  no-debug: 2
  # enforce that duplicate properties are not allowed within the same block
  no-duplicate-properties:
    - 2
    -
      exclude:
        - composes
  # enforce that rulesets are not empty
  no-empty-rulesets: 0
  # enforce that extends are not allowed to be used
  no-extends: 0
  # enforce that ID selectors are not allowed to be used
  no-ids: 2
  # enforce that important declarations are not allowed to be used
  no-important: 0
  # enforce that only valid of hexadecimal values are written
  no-invalid-hex: 2
  # enforce that selectors aren't repeated and that their properties are merged. You may also pass a whitelist of selectors you wish to exclude from merging
  no-mergeable-selectors: 2
  # enforce the correct spelling of CSS properties and prevent the use of unknown CSS properties
  no-misspelled-properties:
    - 2
    -
      extra-properties:
        - composes
        - touch-callout
        - overflow-scrolling
  # enforce that selectors are not allowed to have qualifying elements
  no-qualifying-elements:
    - 2
    - allow-element-with-attribute: true
      allow-element-with-class: true
      allow-element-with-id: false
  no-trailing-zero: 2
  # enforce whether the keyword all can be used with the transition or transition-property property
  no-transition-all: 2
  # enforce that protocols and domains are not used within urls
  no-url-protocols: 2
  # enforce that vendor prefixes are not allowed to be used
  no-vendor-prefixes:
    - 0
    - additional-identifiers: []
      excluded-identifiers: []
  # enforce that @warn statements are not allowed to be used
  no-warn: 2
  # enforce that new declarations must begin on new lines
  one-declaration-per-line: 2
  # enforce whether extends should only include placeholder selectors
  placeholder-in-extend: 2
  # enforce a convention for placeholder names
  placeholder-name-format:
    - 2
    - convention: hyphenatedlowercase
      allow-leading-underscore: true
  # enforce the order in which declarations are written
  property-sort-order:
    - 2
    -
      ignore_unspecified: true
      order:
        - all
        - composes
        - appearance
        - display
        - position
        - top
        - right
        - bottom
        - left
        - float
        - clear
        - overflow
        - overflow-x
        - overflow-y
        - -webkit-overflow-scrolling
        - z-index
        - flex
        - flex-basis
        - flex-direction
        - flex-flow
        - flex-grow
        - flex-shrink
        - flex-wrap
        - align-content
        - align-items
        - align-self
        - justify-content
        - order
        - width
        - min-width
        - max-width
        - height
        - min-height
        - max-height
        - margin
        - margin-top
        - margin-right
        - margin-bottom
        - margin-left
        - padding
        - padding-top
        - padding-right
        - padding-bottom
        - padding-left
        - border
        - border-top
        - border-right
        - border-bottom
        - border-left
        - border-width
        - border-top-width
        - border-right-width
        - border-bottom-width
        - border-left-width
        - border-style
        - border-top-style
        - border-right-style
        - border-bottom-style
        - border-left-style
        - border-radius
        - border-top-left-radius
        - border-top-right-radius
        - border-bottom-left-radius
        - border-bottom-right-radius
        - border-color
        - border-top-color
        - border-right-color
        - border-bottom-color
        - border-left-color
        - border-collapse
        - border-spacing
        - box-sizing
        - box-shadow
        - outline
        - outline-color
        - outline-offset
        - outline-style
        - outline-width
        - background
        - background-attachment
        - background-color
        - background-image
        - background-repeat
        - background-position
        - background-size
        - color
        - font
        - font-family
        - font-size
        - font-smoothing
        - font-style
        - font-variant
        - font-weight
        - letter-spacing
        - line-height
        - list-style
        - text-align
        - text-decoration
        - text-indent
        - text-overflow
        - text-rendering
        - text-shadow
        - text-transform
        - text-wrap
        - white-space
        - word-spacing
        - columns
        - column-gap
        - column-fill
        - column-rule
        - column-span
        - column-count
        - column-width
        - table-layout
        - vertical-align
        - empty-cells
        - caption-side
        - opacity
        - visibility
        - transform
        - transform-box
        - transform-origin
        - transform-style
        - transition
        - transition-delay
        - transition-duration
        - transition-property
        - transition-timing-function
        - animation
        - animation-duration
        - animation-timing-function
        - animation-delay
        - animation-iteration-count
        - animation-direction
        - animation-fill-mode
        - animation-play-state
        - animation-name
        - content
        - quotes
        - cursor
        - speak
  # disallow the use of units not specified in global or per-property. Units specified per-property will override the global units for that property
  property-units:
    - 2
    - global: []
      per-property: {}
  # enforce whether single quotes ('') or double quotes ("") should be used for all strings
  quotes:
    - 2
    - style: single
  # enforce that values in their shorthand form are as concise as specified
  shorthand-values:
    - 0
    - allowed-shorthands:
        - 1
        - 2
        - 3
  # enforce whether selectors should be placed on a new line
  single-line-per-selector: 2
  # enforce whether or not a space should be included after a bang (!)
  space-after-bang:
    - 2
    - include: false
  space-after-colon:
    - 2
    - include: true
  space-after-comma:
    - 2
    - include: true
  space-around-operator:
    - 2
    - include: true
  space-before-bang:
    - 2
    - include: true
  space-before-brace:
    - 2
    - include: true
  space-before-colon:
    - 2
    - include: false
  space-between-parens:
    - 2
    - include: false
  # enforce whether the last declaration in a block should include a semicolon (;) or not (.sass syntax excluded)
  trailing-semicolon:
    - 2
    - include: true
  # enforce that URLs are wrapped in quotes
  url-quotes: 2
  # enforce the use of variables for the values of specified properties. There are no properties by default
  variable-for-property:
    - 0
    - properties:
        - font
        - font-size
  variable-name-format:
    - 2
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  zero-unit:
    - 2
    - include: false
